package com.example.nalone.enumeration;

public enum TypeEvent {
    GAME, GATHER, MULTIMEDIA, MUSIC, PARTY, SCIENCE, SHOP, SHOW, SPORT, ART, ANIMAL, BOOK, ENVIRONMENT, TECHNOLOGY, WELL_BEING, WORK, CAR, CONTEST, CONFERENCE, HEALTH;
}
